
services:
  # api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #   env_file: .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: tourcompanion
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d tourcompanion"]
      interval: 5s
      timeout: 5s
      retries: 5
  test_db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  osrm-foot:
    image: ghcr.io/project-osrm/osrm-backend
    volumes:
      - ./:/data
    command: >
      osrm-routed --algorithm mld /data/data/dolnoslaskie-260323.osrm
    ports:
      - "5000:5000"
      
  redis-commander:
      image: rediscommander/redis-commander:latest
      ports:
        - "8081:8081"
      environment:
        - REDIS_HOSTS=local:redis:6379
  celery-worker:
    build: .
    command: celery -A app.core.celery_app worker -Q narrative -l info --concurrency 1
    env_file: .env
    volumes:
      - .:/app
      - tts_edge_cache:/root/.cache/edge-tts
      - ./audio_files:/app/audio_files
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    runtime: nvidia

  celery-beat:
    build: .
    command: celery -A app.core.celery_app beat -l info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy

  # kokoro-fastapi:
  #     image: ghcr.io/remsky/kokoro-fastapi-cpu:latest 
  #     ports:
  #       - "8880:8880"
  #  kokoro-fastapi:
  #    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest 
  #    ports:
  #      - "9000:8880"
  #    environment:
  #    depends_on:
  #      - redis
  #    deploy:
  #      resources:
  #        reservations:
  #          devices:
  #            - capabilities: [gpu]
  #    runtime: nvidia
volumes:
  pgdata:
  pgdata_test:
  tts_edge_cache: